"base_path" : "."
#"base_url" : ""

#
# Choose file structure in crowdin
# e.g. true or false
#
"preserve_hierarchy": false

#
# Files configuration
#
files: [
 {
  #
  # Source files
  "source" : "/app/src/main/res/values/strings.xml",

  #
  # where translations live
  "translation" : "/app/src/main/res/values-%android_code%/%original_file_name%",

  #
  # Often software projects have custom names for locale directories.
  # crowdin-cli allows you to map your own languages to be understandable by Crowdin.
  #
  "languages_mapping" : {
    "android_code": {
        "de": "de",
        "ru": "ru",
        "fr": "fr",
        "nb": "nb",
        "es-ES": "es"
    }
  },
  
  #
  # files or directories for ignore
  # e.g. ["/**/?.txt", "/**/[0-9].txt", "/**/*\?*.txt"]
  #
  #"ignore" : [],

  #
  # The dest allows you to specify a file name on Crowdin
  # e.g. "/messages.json"
  #
  #"dest" : "",

  #
  # File type
  # e.g. "json"
  #
  #"type" : "",

  #
  # The parameter "update_option" is optional. If it is not set, translations for changed strings will be lost. Useful for typo fixes and minor changes in source strings.
  # e.g. "update_as_unapproved" or "update_without_changes"
  #
  #"update_option" : "",

 },
 {
     "source" : "/resources/playstore/play_store_description.txt",
     "translation": "/resources/playstore/play_store_description_i18n/play_store_description_%android_code%.txt"
 }
]